-- AI Session Hub - Unified neutral session library schema
-- Stores every discovered AI session in one searchable, exportable store.

CREATE TABLE IF NOT EXISTS tools (
    name            TEXT PRIMARY KEY,
    display_name    TEXT NOT NULL,
    adapter_class   TEXT NOT NULL,
    data_path       TEXT,
    enabled         INTEGER DEFAULT 1,
    last_sync_at    TEXT,
    session_count   INTEGER DEFAULT 0,
    total_size_mb   REAL DEFAULT 0.0
);

-- Core sessions table. id is a composite key: "<tool>:<native_session_id>"
-- so sessions from different tools never collide.
CREATE TABLE IF NOT EXISTS sessions (
    id              TEXT PRIMARY KEY,
    tool            TEXT NOT NULL,
    session_id      TEXT NOT NULL,
    title           TEXT,
    project_path    TEXT,
    model           TEXT,
    status          TEXT DEFAULT 'completed',
    started_at      TEXT,
    ended_at        TEXT,
    message_count   INTEGER DEFAULT 0,
    file_path       TEXT,
    file_size_bytes INTEGER,
    file_mtime      REAL,
    raw_metadata    TEXT,

    -- Token / cost accounting (populated by adapters, read by sync.py)
    input_tokens        INTEGER DEFAULT 0,
    output_tokens       INTEGER DEFAULT 0,
    cache_read_tokens   INTEGER DEFAULT 0,
    cache_write_tokens  INTEGER DEFAULT 0,
    reasoning_tokens    INTEGER DEFAULT 0,
    api_call_count      INTEGER DEFAULT 0,

    -- Categorization (populated by core/categorize.py, editable in UI)
    category        TEXT,
    category_confidence REAL DEFAULT 0.0,
    tags            TEXT,

    -- Master prompt (generated by core/master_prompt.py)
    master_prompt   TEXT,

    first_synced_at TEXT NOT NULL DEFAULT (datetime('now')),
    last_synced_at  TEXT NOT NULL DEFAULT (datetime('now')),

    FOREIGN KEY (tool) REFERENCES tools(name)
);

-- Individual messages within sessions.
CREATE TABLE IF NOT EXISTS messages (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    session_fk      TEXT NOT NULL,
    message_id      TEXT,
    role            TEXT NOT NULL,
    content_text    TEXT,
    content_type    TEXT DEFAULT 'text',
    model           TEXT,
    timestamp       TEXT,
    token_input     INTEGER,
    token_output    INTEGER,
    raw_json        TEXT,
    parent_id       TEXT,
    seq             INTEGER DEFAULT 0,

    FOREIGN KEY (session_fk) REFERENCES sessions(id)
);

-- Full-text search virtual table.
CREATE VIRTUAL TABLE IF NOT EXISTS messages_fts USING fts5(
    content_text,
    content='messages',
    content_rowid='id',
    tokenize='unicode61'
);

-- Triggers to keep FTS in sync.
CREATE TRIGGER IF NOT EXISTS messages_ai AFTER INSERT ON messages BEGIN
    INSERT INTO messages_fts(rowid, content_text) VALUES (new.id, new.content_text);
END;

CREATE TRIGGER IF NOT EXISTS messages_ad AFTER DELETE ON messages BEGIN
    INSERT INTO messages_fts(messages_fts, rowid, content_text) VALUES('delete', old.id, old.content_text);
END;

CREATE TRIGGER IF NOT EXISTS messages_au AFTER UPDATE ON messages BEGIN
    INSERT INTO messages_fts(messages_fts, rowid, content_text) VALUES('delete', old.id, old.content_text);
    INSERT INTO messages_fts(rowid, content_text) VALUES (new.id, new.content_text);
END;

-- Sync tracking.
CREATE TABLE IF NOT EXISTS sync_log (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    tool             TEXT NOT NULL,
    sync_started_at  TEXT NOT NULL,
    sync_ended_at    TEXT,
    status           TEXT DEFAULT 'running',
    sessions_found   INTEGER DEFAULT 0,
    sessions_new     INTEGER DEFAULT 0,
    sessions_updated INTEGER DEFAULT 0,
    error_message    TEXT,
    FOREIGN KEY (tool) REFERENCES tools(name)
);

-- Export tracking (neutral -> tool-native).
CREATE TABLE IF NOT EXISTS export_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    session_fk      TEXT NOT NULL,
    target_tool     TEXT NOT NULL,
    exported_at     TEXT NOT NULL DEFAULT (datetime('now')),
    status          TEXT DEFAULT 'ok',
    destination     TEXT,
    error_message   TEXT
);

-- Indexes for common queries.
CREATE INDEX IF NOT EXISTS idx_sessions_tool ON sessions(tool);
CREATE INDEX IF NOT EXISTS idx_sessions_started ON sessions(started_at);
CREATE INDEX IF NOT EXISTS idx_sessions_project ON sessions(project_path);
CREATE INDEX IF NOT EXISTS idx_sessions_category ON sessions(category);
CREATE INDEX IF NOT EXISTS idx_sessions_tool_started ON sessions(tool, started_at);
CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_fk);
CREATE INDEX IF NOT EXISTS idx_messages_role ON messages(role);
CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON messages(timestamp);
